target:
  image: ubuntu-target
  container_name: ubuntu01
  expose:
    - "22"
  volumes:
    - ./.ssh/id_rsa.pub:/home/ubuntu/.ssh/authorized_keys

control:
  image: ansible-control
  container_name: control
  links:
    - target
  volumes:
    - ./.ssh/id_rsa:/root/.ssh/id_rsa
    - ./.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    - .:/ansible/playbooks
  tty: true
